### ISSUE TITLE
Question regarding tokenization

### ISSUE THREAD

**Issue by GokulEpiphany** [buptLinfy/ZSE-SBIR#2]
Thank you for open-sourcing this project.
According to the paper, only sketch images are tokenized by Conv2D to increase receptive field. 
From sa.py, the following line seems to tokenize images and sketches in similar way,

https://github.com/buptLinfy/ZSE-SBIR/blob/e78ee1e0e4ce97e64b0fecb609419466c6f30e50/model/sa.py#L157

Am I missing something obvious?

**Comment by pyh0715** [comment]
Learnable Tokenization没开放吧

**Comment by buptLinfy** [comment]
Thank you for following our research and asking questions!

According to the paper,  our network performs best when using learnable tokenizer only on sketches. But for much easier understanding and implementation, sketches and images pass through the same learnable tokenizer in our public code.
