### ISSUE TITLE
About utils.valid

### ISSUE THREAD

**Issue by wddwgzz** [buptLinfy/ZSE-SBIR#3]
Thanks you for sharing your amazing work.
But I have a question about the code on utils.valid, it's too slow when running the code with all validate data, is there anything can do to make the code on utils.valid more efficient?

**Comment by buptLinfy** [comment]
Thank you for following our research and asking questions!

1. During the inference process, half-precision inference can be turned on, as we already provided in `test.py`.
2. Under the GPU memory, you can multiply `args.test_sk` and `args.test_im` to increase the number of sketches and images in each batch while testing.
