### ISSUE TITLE
the dimension of retrieval token is 512 or 768?

### ISSUE THREAD

**Issue by lcx1505900610** [buptLinfy/ZSE-SBIR#5]
Thank you for opening up this amazing project. But the dimension of the retrieval token in the paper is 512, but after reading the code, I believe that the retrieval token used may have a dimension of 768, or is there an additional operation on the class token to map the 512 dimension token for retrieval

**Comment by buptLinfy** [comment]
Thank you for following our research and asking questions! The dimension of 512 refers primarily to this code:

https://github.com/buptLinfy/ZSE-SBIR/blob/88f87f769208f9de5b08f2d7f0569a8087ee5b4b/model/model.py#L33-L36

As for the retrieval token, there is indeed a small mistake which should be marked as d=768.
