### ISSUE TITLE
How to retrieve images based only one sketch in the provided program?

### ISSUE THREAD

**Issue by numb89757** [buptLinfy/ZSE-SBIR#6]
Thank you for your work. I'm interesting about your Inspiring work. 

May I ask how to retrieve images based a single sketch in the provided program? After reading your code, I don't know how to do local interpretation in one sketch. Could you please give me some guidence on how to retrieve and explain a specific sketch(may draw by myself) using your method?

Looking forward to your reply.

**Comment by buptLinfy** [comment]
Thank you for following our research and asking questions! 

You can customize any sketche or image during the test stage, specifically by changing the path of the input dataset.

https://github.com/buptLinfy/ZSE-SBIR/blob/88f87f769208f9de5b08f2d7f0569a8087ee5b4b/data_utils/preLoad.py#L69-L82

As for the local interpretation, given one sketch as an input to the model, you can analyze and visualize the feature map of `sa_fea` or `ca_fea` in `model.py`.
